[package]
name = "rswave_common"
version = "0.1.0"
authors = ["Lucas Malandrino <lucas.malandrino@gmail.com>"]
edition = "2018"

[dependencies]
int-enum = "^0.4.0"
rkyv = { version = "0.4.1", features = ["strict"] }
rand = "0.8.3"
